admin_evenement:
    resource: "@AdminBundle/Controller/EvenementController.php"
    type:     annotation

admin_item:
    resource: "@AdminBundle/Controller/ItemController.php"
    type:     annotation

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /base

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

admin_commentaire:
    resource: "@AdminBundle/Controller/CommentaireController.php"
    type:     annotation

admin_adresse:
    resource: "@AdminBundle/Controller/AdresseController.php"
    type:     annotation

admin_categorie:
    resource: "@AdminBundle/Controller/CategorieController.php"
    type:     annotation

admin_item:
    resource: "@AdminBundle/Controller/ItemController.php"
    type:     annotation

lambda:
    resource: "@LambdaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
