# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
security:
    providers:
        in_memory:
            memory: ~
        user_db:
            entity:
                class: Lambda\LambdaBundle\Entity\User
                property: username
            
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        Lambda\LambdaBundle\Entity\User: bcrypt
        


        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user_db
            anonymous: ~
            form_login:
                # submit the login form here
                login_path: /login
                # submit the login form here
                check_path: /login
                username_parameter: _username
                password_parameter: _password
                default_target_path: /
            logout:
                path: /logout
                target: /
                
                
        default:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
