base_homepage:
    path: /
    defaults: { _controller: BaseBundle:Default:index }
    
profil:
    path: /profil
    defaults: { _controller: BaseBundle:Profil:index }
    
adresse:
    path: /adresse
    defaults: { _controller: BaseBundle:Adressebase:index }
    
groupe:
    path: /groupe
    defaults: { _controller: BaseBundle:Groupe:index }
