lambda_homepage:
    path: /
    defaults: { _controller: LambdaBundle:Default:index }
    
user:
    path: /user
    defaults: { _controller: LambdaBundle:User:index }

login:
    path: /login
    defaults: { _controller: LambdaBundle:Security:login }
    
logout:
    path: /logout
    defaults: { _controller: LambdaBundle:Security:logout }

register:
    path: /register/
    defaults: { _controller: LambdaBundle:Security:register }
    
#admin:
#    path: /admin
#    defaults: { _controller: AdminBundle:Default:index }
#    
#base:
#    path: /base
#    defaults: { _controller: BaseBundle:Default:index }